name: release

on:
  workflow_dispatch:
  push:
    branches:
      - preview
      - main
      - v*.x
    tags-ignore:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
                                    
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Update package.json
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          # Update the version number in package.json
          node -e "const fs = require('fs');
          const package = JSON.parse(fs.readFileSync('package.json'));
          package.version = '${{ steps.semantic.outputs.new_release_version }}';
          fs.writeFileSync('package.json', JSON.stringify(package, null, 2));"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: bump version in package.json"
          push: true
