name: release

on:
  workflow_dispatch:
  push:
    branches:
      - preview
      - main
      - v*.x
    tags-ignore:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5  # It is recommended to specify a version range
                                    # for semantic-release when using
                                    # semantic-release-action lower than @v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
